name: flutter_resume_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pdf: ^3.11.2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  share_plus: ^10.1.4
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.0.7
  image_cropper: ^9.1.0
  google_fonts: ^6.0.0
  twinkling_stars: ^1.0.2
  audioplayers:
  confetti:
  flutter_screenutil: 
  flutter_device_type:
  flutter_pdfview: ^1.3.1
  syncfusion_flutter_pdfviewer: ^29.2.9
  provider: ^6.1.1
  uuid: ^4.0.0
  flutter_cached_pdfview: ^0.4.3
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - images/
    - assets/icons/email_white.png
    - assets/icons/phone_white.png
    - assets/icons/address_white.png
    - assets/icons/web_white.png
    - assets/icons/email_back.png
    - assets/icons/phone_back.png
    - assets/icons/address_back.png
    - assets/icons/web_back.png
    - assets/fonts/
    - assets/fonts/SweetLollipop.ttf
    - assets/fonts/Mulish-Regular.ttf
    - assets/fonts/Orbitron.ttf
    - assets/fonts/Fireplace_PERSONAL_USE_ONLY.ttf
    - assets/fonts/SOLAR_SPACE_DEMO.ttf
    - assets/fonts/MidnightConstellations.ttf
    - assets/images/
    - assets/onboarding-style-images/
    - assets/icons_image/
    - assets/ResumeTipItem/
  fonts:
    - family: SweetLollipop
      fonts:
        - asset: assets/fonts/SweetLollipop.ttf
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron.ttf
    - family: Fireplace
      fonts:
        - asset: assets/fonts/Fireplace_PERSONAL_USE_ONLY.ttf
    - family: SOLAR_SPACE_DEMO
      fonts:
        - asset: assets/fonts/SOLAR_SPACE_DEMO.ttf
    - family: MidnightConstellations
      fonts:
        - asset: assets/fonts/MidnightConstellations.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logoresume.png"
  min_sdk_android: 21
  remove_alpha_ios: true